import Link from "next/link";
import { ArrowRight, Download, Heart, BookOpen, Flower2, Sun, Sparkles, Compass, PenLine, Check } from "lucide-react";
import { getCategories, getFaqs, getPublishedProducts, getSettings, getTestimonials } from "@/lib/store";
import ProductCard from "@/components/ProductCard";
import FAQAccordion from "@/components/FAQAccordion";
import Newsletter from "@/components/Newsletter";

export default async function HomePage() {
  const [settings, categories, products, ebooks, freebies, faqItems, testimonials] = await Promise.all([getSettings(), getCategories(), getPublishedProducts({ featured: true, type: "journal", paidOnly: true }), getPublishedProducts({ type: "ebook", featured: true, limit: 4 }), getPublishedProducts({ free: true, limit: 4 }), getFaqs(), getTestimonials()]);
  const categoryIcons = [Flower2, Sun, Heart, Compass];
  const defaultTitle = settings.heroTitle === "Make space for the person you're becoming.";
  return <main>
    <section className="hero"><div className="container hero-grid">
      <div className="hero-copy"><span className="eyebrow">{settings.heroEyebrow}</span><h1 className="hero-title">{defaultTitle ? <>Make space for the <em>person you&apos;re becoming.</em></> : settings.heroTitle}</h1><p className="hero-description">{settings.heroDescription}</p><div className="hero-buttons"><Link href="/shop" className="button">Explore the journals <ArrowRight size={16} /></Link><Link href="#how-it-works" className="text-link">How it works <ArrowRight size={15} /></Link></div><div className="hero-footnote"><span className="line" />Thoughtful pages for your everyday life. ♡</div></div>
      <div className="hero-visual"><div className="hero-blob" /><span className="hero-star">✳</span><img className="hero-photo" src={settings.heroImage} alt="An open journal beside a cup of tea in warm sunlight" /><div className="hero-note"><span>✳</span><p>your story<br />starts here.</p></div><div className="hero-seal">SLOW DOWN<br />& FEEL<br />MORE ✦</div></div>
    </div></section>
    <div className="benefits"><div className="container benefit-grid"><div className="benefit"><Download size={22} strokeWidth={1.5} /><div><strong>Instantly yours</strong><small>Download right after checkout</small></div></div><div className="benefit"><Heart size={22} strokeWidth={1.5} /><div><strong>Made with intention</strong><small>Thoughtful prompts, beautiful pages</small></div></div><div className="benefit"><BookOpen size={22} strokeWidth={1.5} /><div><strong>Journal your way</strong><small>Print it or use it digitally</small></div></div></div></div>
    <section className="section"><div className="container"><div className="section-top"><div><span className="eyebrow">FIND YOUR KIND OF SPACE</span><h2 className="section-title">A journal for every<br /><em style={{ fontWeight: 400 }}>chapter of you.</em></h2></div><Link href="/categories" className="text-link">All categories <ArrowRight size={15} /></Link></div><div className="category-grid">{categories.map((category, index) => { const Icon = categoryIcons[index % categoryIcons.length]; return <Link href={`/categories/${category.slug}`} className={`category-tile ${category.color}`} key={category.id}><span className="category-number">0{index + 1} / EXPLORE</span><div className="category-illustration"><Icon /></div><div className="category-bottom"><div><h3>{category.name}</h3><p>{category.description}</p></div><span className="category-arrow"><ArrowRight size={15} /></span></div></Link>; })}</div></div></section>
    <section className="section-sm" style={{ background: "#fdfbf7" }}><div className="container"><div className="section-top"><div><span className="eyebrow">WELL-LOVED JOURNALS</span><h2 className="section-title">{settings.featuredTitle}</h2><p className="section-lead" style={{ margin: "15px 0 0" }}>Your next little ritual might be right here.</p></div><Link href="/shop" className="text-link">Shop all journals <ArrowRight size={15} /></Link></div><div className="product-grid">{products.slice(0, 4).map((product) => <ProductCard key={product.id} product={product} categoryName={categories.find((category) => category.id === product.categoryId)?.name} />)}</div></div></section>
    {ebooks.length > 0 && <section className="section ebook-section"><div className="container"><div className="section-top"><div><span className="eyebrow" style={{ color: "#c9a78f" }}>THE READING ROOM · E-BOOKS</span><h2 className="section-title" style={{ color: "#f6f1e6" }}>Books to read <em style={{ fontWeight: 400, color: "#e7b8a4" }}>anywhere.</em></h2><p className="section-lead" style={{ margin: "15px 0 0", color: "#c5d0c4" }}>Read a free sample, buy in seconds, and start reading instantly online — or download the PDF to keep.</p></div><Link href="/ebooks" className="text-link" style={{ color: "#f6f1e6", borderColor: "#f6f1e6" }}>Browse all e-books <ArrowRight size={15} /></Link></div><div className="product-grid ebook-grid">{ebooks.map((book) => <ProductCard key={book.id} product={book} />)}</div></div></section>}
    {freebies.length > 0 && <section className="section-sm free-section"><div className="container"><div className="section-top"><div><span className="eyebrow">A LITTLE GIFT · FREE LIBRARY</span><h2 className="section-title">Start for free, <em style={{ fontWeight: 400 }}>today.</em></h2><p className="section-lead" style={{ margin: "15px 0 0" }}>Free printables, starter journals, and classic books. Just your email — no card, ever.</p></div><Link href="/free" className="text-link">See the free library <ArrowRight size={15} /></Link></div><div className="product-grid">{freebies.map((item) => <ProductCard key={item.id} product={item} />)}</div></div></section>}
    <section className="section story-section"><div className="container story-grid"><div className="story-photo-wrap"><img className="story-photo" src={settings.aboutImage} alt="A quiet moment writing in a journal" /><div className="story-sticker">a little<br />space for<br />you ♡</div></div><div className="story-copy"><span className="eyebrow">A NOTE FROM US</span><h2 className="section-title">{settings.aboutTitle}</h2><p>{settings.aboutText}</p><div className="story-points"><div className="story-point"><Check size={17} />Made to meet you exactly where you are</div><div className="story-point"><Check size={17} />Beautifully simple, never overwhelming</div><div className="story-point"><Check size={17} />A small practice with a big impact</div></div><Link href="/about" className="button">Get to know us <ArrowRight size={16} /></Link></div></div></section>
    <section className="section" id="how-it-works"><div className="container"><div style={{ textAlign: "center" }}><span className="eyebrow">SIMPLE AS ONE, TWO, YOU</span><h2 className="section-title" style={{ margin: "18px 0 0" }}>A little space, in three steps.</h2></div><div className="how-grid"><div className="how-step"><div className="how-number">01</div><h3>Find your journal</h3><p>Choose the pages that speak to this season of your life. There&apos;s no wrong place to start.</p></div><div className="how-step"><div className="how-number">02</div><h3>Download instantly</h3><p>Your journal is ready right after checkout. No waiting, no shipping, just a fresh start.</p></div><div className="how-step"><div className="how-number">03</div><h3>Make it yours</h3><p>Print your pages or use them on your favorite device. Come back to them whenever you need.</p></div></div></div></section>
    {testimonials[0] && <section className="quote-section"><div className="quote-mark">“</div><blockquote className="quote-text">{testimonials[0].quote}</blockquote><div className="quote-by">— {testimonials[0].name} · {testimonials[0].detail}</div></section>}
    <section className="section"><div className="container"><div style={{ textAlign: "center", marginBottom: 32 }}><span className="eyebrow">GOOD TO KNOW</span><h2 className="section-title" style={{ margin: "16px 0 0" }}>A few things you might wonder.</h2></div><FAQAccordion items={faqItems.slice(0, 4)} /><div style={{ textAlign: "center", marginTop: 30 }}><Link href="/faq" className="text-link">More questions? Visit our FAQs <ArrowRight size={15} /></Link></div></div></section>
    <Newsletter />
  </main>;
}
