"use client";

import { useCallback, useEffect, useState } from "react";
import Link from "next/link";
import { LayoutDashboard, Package, Grid2X2, ReceiptText, Users, TicketPercent, PanelsTopLeft, Settings, Mail, ArrowUpRight, Plus, Pencil, Trash2, Search, DollarSign, ShoppingBag, TrendingUp, Eye, X, MessageSquare, UserRound, ExternalLink, Download, ArrowRight, CircleHelp, Star, ShieldCheck, Database, Send, BookOpen, Upload } from "lucide-react";
import type { LucideIcon } from "lucide-react";
import ProductArt from "@/components/ProductArt";
import LogoutButton from "@/components/LogoutButton";
import { formatDate, formatPrice } from "@/lib/format";
import { GenericEditor, ProductEditor, SettingsEditor } from "@/components/admin/Editors";
import { NavEditor, SectionsBuilder } from "@/components/admin/SiteEditors";
import type { AdminData, AdminOrder, AdminProduct, AdminCustomer, AdminMessage } from "@/components/admin/types";

type Tab = "dashboard" | "products" | "categories" | "orders" | "customers" | "coupons" | "content" | "messages" | "subscribers" | "settings";
type ContentTab = "home" | "nav" | "sections" | "faqs" | "testimonials" | "policies";
const nav: { id: Tab; label: string; icon: LucideIcon }[] = [
  { id: "dashboard", label: "Overview", icon: LayoutDashboard }, { id: "products", label: "Products", icon: Package }, { id: "categories", label: "Categories", icon: Grid2X2 }, { id: "orders", label: "Orders", icon: ReceiptText }, { id: "customers", label: "Customers", icon: Users }, { id: "coupons", label: "Coupons", icon: TicketPercent }, { id: "content", label: "Content & pages", icon: PanelsTopLeft }, { id: "messages", label: "Messages", icon: Mail }, { id: "subscribers", label: "Subscribers", icon: Send }, { id: "settings", label: "Settings", icon: Settings },
];
const titles: Record<Tab, string> = { dashboard: "Good to see you.", products: "Your journals", categories: "Categories", orders: "Orders", customers: "Customers", coupons: "Coupons & offers", content: "Content & pages", messages: "Your inbox", subscribers: "Subscribers", settings: "Store settings" };
const descriptions: Record<Tab, string> = { dashboard: "Here's what's happening in your little corner of the internet.", products: "Create, edit, and publish your digital journals.", categories: "Organize your journals into meaningful collections.", orders: "Every purchase, all in one place.", customers: "The people who make this community possible.", coupons: "Little offers to share with your customers.", content: "Make the site feel even more like you.", messages: "Notes from your customers and visitors.", subscribers: "People who asked to hear from you.", settings: "Your brand, connections, and store details." };

async function api(url: string, method = "GET", body?: unknown) {
  const response = await fetch(url, { method, headers: body !== undefined ? { "Content-Type": "application/json" } : undefined, body: body !== undefined ? JSON.stringify(body) : undefined, cache: "no-store" });
  const result = await response.json().catch(() => ({}));
  if (!response.ok) throw new Error(result.error || "Something went wrong. Please try again.");
  return result;
}

function Modal({ title, children, onClose }: { title: string; children: React.ReactNode; onClose: () => void }) {
  return <div className="admin-modal-backdrop" onMouseDown={(event) => { if (event.target === event.currentTarget) onClose(); }}><div className="admin-modal"><div className="admin-modal-head"><h2>{title}</h2><button onClick={onClose} aria-label="Close modal"><X size={20} /></button></div>{children}</div></div>;
}
function Status({ value }: { value: string }) { return <span className={`admin-pill ${["draft", "pending", "failed", "cancelled", "refunded", "disabled"].includes(value) ? value : ""}`}>{value}</span>; }
function TableEmpty({ message }: { message: string }) { return <div className="admin-empty">✳ &nbsp; {message}</div>; }

export default function AdminApp({ adminName }: { adminName: string }) {
  const [data, setData] = useState<AdminData | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [notice, setNotice] = useState("");
  const [tab, setTab] = useState<Tab>("dashboard"); const [contentTab, setContentTab] = useState<ContentTab>("home"); const [search, setSearch] = useState(""); const [productFilter, setProductFilter] = useState<"all" | "journal" | "ebook" | "free">("all");
  const [modal, setModal] = useState<{ resource: string; item?: unknown } | null>(null);
  const reload = useCallback(async () => { const result = await api("/api/admin/data"); setData(result as AdminData); }, []);
  useEffect(() => { const wanted = new URLSearchParams(window.location.search).get("tab") as Tab | null; if (wanted && nav.some((item) => item.id === wanted)) setTab(wanted); reload().catch((err) => setError(err.message)).finally(() => setLoading(false)); }, [reload]);
  function switchTab(next: Tab) { setTab(next); setSearch(""); setNotice(""); window.history.replaceState(null, "", next === "dashboard" ? "/admin" : `/admin?tab=${next}`); }
  function flash(message: string) { setNotice(message); setTimeout(() => setNotice(""), 4000); }
  async function saveGeneric(resource: string, item: { id?: string } | undefined, payload: Record<string, unknown>) { await api(`/api/admin/${resource}${item?.id ? `/${item.id}` : ""}`, item?.id ? "PATCH" : "POST", payload); await reload(); setModal(null); flash(`${resource.slice(0, -1)} saved successfully.`); }
  async function upload(file: File, kind: string, productId?: string, options?: Record<string, unknown>) {
    const form = new FormData(); form.append("file", file); form.append("kind", kind); if (productId) form.append("productId", productId); if (options) Object.entries(options).forEach(([key, value]) => form.append(key, String(value)));
    const response = await fetch("/api/admin/upload", { method: "POST", body: form }); const result = await response.json(); if (!response.ok) throw new Error(result.error || "Upload failed."); return result;
  }
  async function saveProduct(payload: Record<string, unknown>, cover: File | null, pdf: File | null, previews: File[]) {
    const existing = modal?.item as AdminProduct | undefined;
    const desiredStatus = payload.status;
    const input = { ...payload };
    if (cover) input.coverImage = (await upload(cover, "image")).url;
    if (desiredStatus === "published" && !existing?.file && !pdf) throw new Error("Upload a private PDF before publishing this journal.");
    if (pdf && !existing?.file) input.status = "draft";
    let id: string;
    if (existing) { await api(`/api/admin/products/${existing.id}`, "PATCH", input); id = existing.id; }
    else { const created = await api("/api/admin/products", "POST", input); id = created.item.id; }
    if (pdf) await upload(pdf, "pdf", id, { maxDownloads: payload.maxDownloads || 5, expiryDays: payload.expiryDays || 30, allowRedownload: payload.allowRedownload !== false, previewPages: payload.previewPages ?? 3 });
    for (const preview of previews) await upload(preview, "preview", id);
    if (desiredStatus === "published" && (!existing || !existing.file)) await api(`/api/admin/products/${id}`, "PATCH", { ...input, status: "published" });
    await reload(); setModal(null); flash("Journal saved successfully.");
  }
  async function deleteResource(resource: string, id: string, label: string) { if (!window.confirm(`Remove ${label}? Products with existing orders will be unpublished instead of deleted.`)) return; try { await api(`/api/admin/${resource}/${id}`, "DELETE"); await reload(); flash(`${label} removed.`); } catch (err) { setError(err instanceof Error ? err.message : "Could not remove item."); } }
  async function action(resource: string, id: string, payload: Record<string, unknown>, confirmMessage?: string) { if (confirmMessage && !window.confirm(confirmMessage)) return; try { await api(`/api/admin/${resource}/${id}`, "PATCH", payload); await reload(); setModal(null); flash("Changes saved."); } catch (err) { setError(err instanceof Error ? err.message : "Action failed."); } }
  const headerAction = (label: string, resource: string) => <button className="button button-small" onClick={() => setModal({ resource })}><Plus size={15} /> {label}</button>;
  const editButtons = (resource: string, item: { id: string; name?: string; code?: string; question?: string }) => <div className="admin-actions"><button className="admin-icon-btn" title="Edit" onClick={() => setModal({ resource, item })}><Pencil size={14} /></button><button className="admin-icon-btn danger" title="Delete" onClick={() => deleteResource(resource, item.id, item.name || item.code || item.question || "this item")}><Trash2 size={14} /></button></div>;
  const panelTitle = (title: string, subtitle?: string) => <div className="admin-panel-head"><div><h2>{title}</h2>{subtitle && <p>{subtitle}</p>}</div></div>;
  const productMini = (product: { name: string; theme?: string; coverImage?: string | null }) => <div className="product-mini"><div className="product-mini-art"><ProductArt product={{ name: product.name, theme: product.theme || "rose", coverImage: product.coverImage }} /></div><strong>{product.name}</strong></div>;
  const filtered = (value: string) => value.toLowerCase().includes(search.toLowerCase());

  function dashboard() {
    if (!data) return null;
    const stats = data.stats; const max = Math.max(...stats.chart.map((point) => point.value), 1);
    const statCards: { label: string; value: string; note: string; icon: LucideIcon }[] = [
      { label: "Total revenue", value: formatPrice(stats.revenue), note: "From completed payments", icon: DollarSign },
      { label: "Paid orders", value: String(stats.orderCount), note: `${stats.totalOrders} checkouts started`, icon: ShoppingBag },
      { label: "Customers", value: String(stats.customerCount), note: "Registered accounts", icon: Users },
      { label: "Published & draft", value: String(stats.productCount), note: "Digital journals", icon: Package },
    ];
    return <><div className="admin-cards">{statCards.map((card) => { const Icon = card.icon; return <div className="admin-stat" key={card.label}><div className="admin-stat-top"><span>{card.label}</span><Icon size={17} /></div><strong>{card.value}</strong><small>{card.note}</small></div>; })}</div><div className="admin-dashboard-grid"><div className="admin-panel">{panelTitle("Sales over the last 7 days", `Checkout conversion: ${stats.conversion}%`)}<div className="admin-chart">{stats.chart.map((point, index) => <div className="admin-chart-col" key={index}><div className="admin-chart-bar" title={`${point.label}: ${formatPrice(point.value)}`} style={{ height: `${Math.max(3, point.value / max * 100)}%`, background: point.value ? "#85a98e" : "#e4ebe3" }} /><span>{point.label}</span></div>)}</div></div><div className="admin-panel">{panelTitle("Top journals", "By number of paid orders")}{stats.topProducts.length ? <div className="admin-table-wrap"><table className="admin-table" style={{ minWidth: 0 }}><thead><tr><th>Journal</th><th>Sales</th></tr></thead><tbody>{stats.topProducts.map((product) => <tr key={product.name}><td><strong>{product.name}</strong></td><td>{product.sales}</td></tr>)}</tbody></table></div> : <TableEmpty message="Your bestsellers will show up here." />}</div></div><div className="admin-panel" style={{ marginTop: 17 }}><div className="admin-panel-head"><div><h2>Recent orders</h2><p>A quick look at your latest purchases</p></div><button className="text-link" onClick={() => switchTab("orders")}>View all <ArrowRight size={13} /></button></div>{data.orders.length ? <div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Order</th><th>Customer</th><th>Date</th><th>Total</th><th>Payment</th></tr></thead><tbody>{data.orders.slice(0, 5).map((order) => <tr key={order.id}><td><strong>{order.orderNumber}</strong></td><td>{order.customerName}</td><td>{formatDate(order.createdAt)}</td><td><strong>{formatPrice(order.total)}</strong></td><td><Status value={order.paymentStatus} /></td></tr>)}</tbody></table></div> : <TableEmpty message="New orders will appear here as soon as they arrive." />}</div></>;
  }
  function productList() {
    if (!data) return null; const list = data.products.filter((product) => (filtered(product.name) || filtered(product.slug) || filtered(product.author || "")) && (productFilter === "all" || (productFilter === "free" ? (product.salePrice ?? product.price) === 0 : product.type === productFilter)));
    return <><div className="admin-title-row"><div className="admin-tabs" style={{ border: 0, margin: 0 }}>{([["all", "All"], ["journal", "Journals"], ["ebook", "E-books"], ["free", "Free items"]] as const).map(([id, label]) => <button key={id} className={productFilter === id ? "active" : ""} onClick={() => setProductFilter(id)}>{label} ({id === "all" ? data.products.length : id === "free" ? data.products.filter((p) => (p.salePrice ?? p.price) === 0).length : data.products.filter((p) => p.type === id).length})</button>)}</div><div>{headerAction("Add product", "products")}</div></div><div className="admin-toolbar"><Search size={16} color="#91a094" /><input className="input" placeholder="Search titles or authors..." value={search} onChange={(e) => setSearch(e.target.value)} /></div><div className="admin-panel"><div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Product</th><th>Type</th><th>Price</th><th>PDF · Sample</th><th>Status</th><th>Actions</th></tr></thead><tbody>{list.map((product) => <tr key={product.id}><td>{productMini(product)}{product.author && <small style={{ display: "block", marginLeft: 48 }}>by {product.author}</small>}</td><td><span className="admin-pill" style={{ background: product.type === "ebook" ? "#efe6f3" : "#e8f2e9", color: product.type === "ebook" ? "#7a5f8c" : "#4f8058" }}>{product.type === "ebook" ? "E-book" : "Journal"}</span><br /><small>{data.categories.find((category) => category.id === product.categoryId)?.name || ""}</small></td><td><strong>{(product.salePrice ?? product.price) === 0 ? "Free" : formatPrice(product.salePrice ?? product.price)}</strong>{product.salePrice !== null && <del style={{ marginLeft: 6, color: "#a7b1a7" }}>{formatPrice(product.price)}</del>}</td><td>{product.file ? <span style={{ color: "#6a966e" }}>✓ Ready · {product.file.previewPages} sample pg</span> : <span style={{ color: "#b17b61" }}>Missing PDF</span>}</td><td><Status value={product.status} /></td><td>{editButtons("products", product)}</td></tr>)}</tbody></table></div>{!list.length && <TableEmpty message="No journals here yet. Create your first one!" />}<div className="admin-pagination">Showing {list.length} of {data.products.length} journals</div></div></>;
  }
  function categoryList() {
    if (!data) return null;
    return <><div className="admin-title-row"><div />{headerAction("Add category", "categories")}</div><div className="admin-panel"><div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Category</th><th>Description</th><th>Products</th><th>Order</th><th>Actions</th></tr></thead><tbody>{data.categories.map((category) => <tr key={category.id}><td><strong>{category.name}</strong><br /><small>/{category.slug}</small></td><td>{category.description}</td><td>{data.products.filter((product) => product.categoryId === category.id).length}</td><td>{category.sortOrder}</td><td>{editButtons("categories", category)}</td></tr>)}</tbody></table></div></div></>;
  }
  function orderList() {
    if (!data) return null; const list = data.orders.filter((order) => filtered(order.orderNumber) || filtered(order.email) || filtered(order.customerName));
    return <><div className="admin-toolbar"><Search size={16} color="#91a094" /><input className="input" placeholder="Search order, name, or email..." value={search} onChange={(e) => setSearch(e.target.value)} /></div><div className="admin-panel"><div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Order</th><th>Customer</th><th>Date</th><th>Amount</th><th>Payment</th><th>Order</th><th>Details</th></tr></thead><tbody>{list.map((order) => <tr key={order.id}><td><strong>{order.orderNumber}</strong><br /><small>{order.items.length} item(s)</small></td><td><strong>{order.customerName}</strong><br /><small>{order.email}</small></td><td>{formatDate(order.createdAt)}</td><td><strong>{formatPrice(order.total)}</strong></td><td><Status value={order.paymentStatus} /></td><td><Status value={order.status} /></td><td><button className="admin-icon-btn" onClick={() => setModal({ resource: "order", item: order })} title="View order"><Eye size={15} /></button></td></tr>)}</tbody></table></div>{!list.length && <TableEmpty message="Orders will show up here after checkout." />}<div className="admin-pagination">{list.length} orders</div></div></>;
  }
  function customerList() {
    if (!data) return null; const list = data.customers.filter((customer) => customer.role === "customer" && (filtered(customer.name) || filtered(customer.email)));
    return <><div className="admin-toolbar"><Search size={16} color="#91a094" /><input className="input" placeholder="Search customers..." value={search} onChange={(e) => setSearch(e.target.value)} /></div><div className="admin-panel"><div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Customer</th><th>Joined</th><th>Orders</th><th>Total spent</th><th>Status</th><th>Details</th></tr></thead><tbody>{list.map((customer) => <tr key={customer.id}><td><strong>{customer.name}</strong><br /><small>{customer.email}</small></td><td>{formatDate(customer.createdAt)}</td><td>{customer.orderCount}</td><td>{formatPrice(customer.totalSpent)}</td><td><Status value={customer.status} /></td><td><button className="admin-icon-btn" onClick={() => setModal({ resource: "customer", item: customer })}><Eye size={15} /></button></td></tr>)}</tbody></table></div>{!list.length && <TableEmpty message="Customer accounts will appear here." />}</div></>;
  }
  function couponList() {
    if (!data) return null;
    return <><div className="admin-title-row"><div />{headerAction("Create coupon", "coupons")}</div><div className="admin-panel"><div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Code</th><th>Discount</th><th>Uses</th><th>Expires</th><th>Status</th><th>Actions</th></tr></thead><tbody>{data.coupons.map((coupon) => <tr key={coupon.id}><td><strong>{coupon.code}</strong></td><td>{coupon.type === "percentage" ? `${coupon.value}%` : formatPrice(coupon.value)}</td><td>{coupon.usedCount}{coupon.usageLimit ? ` / ${coupon.usageLimit}` : ""}</td><td>{coupon.expiresAt ? formatDate(coupon.expiresAt) : "Never"}</td><td><Status value={coupon.active ? "active" : "disabled"} /></td><td>{editButtons("coupons", coupon)}</td></tr>)}</tbody></table></div>{!data.coupons.length && <TableEmpty message="Create a coupon to surprise your customers." />}</div></>;
  }
  function content() {
    if (!data) return null;
    return <><div className="admin-tabs">{([["home", "Homepage & about"], ["nav", "Navigation & footer"], ["sections", "Homepage sections"], ["faqs", "FAQs"], ["testimonials", "Testimonials"], ["policies", "Policies"]] as [ContentTab, string][]).map(([id, label]) => <button key={id} className={contentTab === id ? "active" : ""} onClick={() => setContentTab(id)}>{label}</button>)}</div>{contentTab === "nav" && <div className="admin-panel">{panelTitle("Navigation & footer links", "Add, remove, rename and reorder — applies to every page once published.")}<NavEditor settings={data.settings as unknown as Record<string, unknown>} onSave={saveSettings} /></div>}{contentTab === "sections" && <div className="admin-panel">{panelTitle("Homepage sections", "Show, hide and reorder the bands on your homepage.")}<SectionsBuilder settings={data.settings as unknown as Record<string, unknown>} onSave={saveSettings} /></div>}{contentTab === "home" && <div className="admin-panel">{panelTitle("Edit your storefront", "Changes appear immediately on your website.")}<SettingsEditor key="home" section="home" settings={data.settings} onSave={async (payload) => { await api("/api/admin/settings", "PUT", payload); await reload(); }} /></div>}{contentTab === "policies" && <div className="admin-panel">{panelTitle("Your policy pages", "Privacy, terms, and refunds") }<SettingsEditor key="policies" section="policies" settings={data.settings} onSave={async (payload) => { await api("/api/admin/settings", "PUT", payload); await reload(); }} /></div>}{contentTab === "faqs" && <><div className="admin-title-row"><div />{headerAction("Add FAQ", "faqs")}</div><div className="admin-panel"><div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Question</th><th>Answer</th><th>Order</th><th>Visible</th><th>Actions</th></tr></thead><tbody>{data.faqs.map((faq) => <tr key={faq.id}><td><strong>{faq.question}</strong></td><td style={{ maxWidth: 270 }}>{faq.answer.slice(0, 92)}{faq.answer.length > 92 ? "..." : ""}</td><td>{faq.sortOrder}</td><td><Status value={faq.active ? "active" : "disabled"} /></td><td>{editButtons("faqs", faq)}</td></tr>)}</tbody></table></div></div></>}{contentTab === "testimonials" && <><div className="admin-title-row"><div />{headerAction("Add testimonial", "testimonials")}</div><div className="admin-panel"><div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Customer</th><th>Quote</th><th>Visible</th><th>Actions</th></tr></thead><tbody>{data.testimonials.map((testimonial) => <tr key={testimonial.id}><td><strong>{testimonial.name}</strong><br /><small>{testimonial.detail}</small></td><td style={{ maxWidth: 440 }}>{testimonial.quote}</td><td><Status value={testimonial.active ? "active" : "disabled"} /></td><td>{editButtons("testimonials", testimonial)}</td></tr>)}</tbody></table></div></div></>}</>;
  }
  function messages() {
    if (!data) return null;
    return <div className="admin-panel"><div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>From</th><th>Subject</th><th>Message</th><th>Date</th><th>Status</th><th>Open</th></tr></thead><tbody>{data.messages.map((message) => <tr key={message.id}><td><strong>{message.name}</strong><br /><small>{message.email}</small></td><td><strong>{message.subject}</strong></td><td style={{ maxWidth: 260 }}>{message.message.slice(0, 70)}...</td><td>{formatDate(message.createdAt)}</td><td><Status value={message.status} /></td><td><button className="admin-icon-btn" onClick={() => { setModal({ resource: "message", item: message }); if (message.status !== "read") action("messages", message.id, { status: "read" }).then(() => setModal({ resource: "message", item: { ...message, status: "read" } })); }}><Eye size={15} /></button></td></tr>)}</tbody></table></div>{!data.messages.length && <TableEmpty message="Notes from the contact form will appear here." />}</div>;
  }
  function subscribers() { if (!data) return null; return <div className="admin-panel">{panelTitle("Newsletter subscribers", `${data.subscribers.length} people on your list`)}<div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Email</th><th>Joined</th></tr></thead><tbody>{data.subscribers.map((subscriber) => <tr key={subscriber.id}><td><strong>{subscriber.email}</strong></td><td>{formatDate(subscriber.createdAt)}</td></tr>)}</tbody></table></div>{!data.subscribers.length && <TableEmpty message="Newsletter signups will appear here." />}</div>; }
  function settings() { if (!data) return null; return <><div className="admin-panel">{panelTitle("Brand & contact details", "Make Softly your own.")}<SettingsEditor key="brand" section="brand" settings={data.settings} onSave={async (payload) => { await api("/api/admin/settings", "PUT", payload); await reload(); }} /></div><div className="admin-panel">{panelTitle("Integrations", "Secrets are configured on the server, never in the browser.")}<div style={{ padding: 22, display: "grid", gap: 15 }}><div className="notice demo"><strong>Store mode:</strong> {data.integrations.demo ? "Preview checkout is active. No real money is collected." : "Stripe payments are active."} Configure STRIPE_SECRET_KEY and STRIPE_WEBHOOK_SECRET before launching.</div><div style={{ display: "flex", alignItems: "center", gap: 12, fontSize: 12 }}><ShieldCheck size={18} color="#789b80" /><strong>Stripe payments & webhook</strong><Status value={data.integrations.stripe ? "connected" : "not connected"} /></div><div style={{ display: "flex", alignItems: "center", gap: 12, fontSize: 12 }}><Mail size={18} color="#789b80" /><strong>Transactional email (Resend)</strong><Status value={data.integrations.email ? "connected" : "not connected"} /></div><div style={{ display: "flex", alignItems: "center", gap: 12, fontSize: 12 }}><Database size={18} color="#789b80" /><strong>Private R2 storage</strong><Status value={data.integrations.storage ? "connected" : "local preview"} /></div><p className="muted" style={{ fontSize: 11, lineHeight: 1.7 }}>Currency: USD. Set SITE_URL, STRIPE_SECRET_KEY, STRIPE_WEBHOOK_SECRET, RESEND_API_KEY, EMAIL_FROM, DOWNLOAD_SECRET, and R2 credentials in your deployment environment. PDF files are never publicly linked.</p></div></div></>; }

  // ---- draft / preview / publish (site edits are DB-driven, no redeploy) ----
  const draftObject = ((data?.settings as unknown) as Record<string, unknown> | undefined)?.settingsDraft;
  const hasDraft = !!draftObject && Object.keys(draftObject).length > 0;
  async function saveSettings(payload: Record<string, unknown>) { await api("/api/admin/settings", "PUT", { mode: "draft", ...payload }); await reload(); }
  async function publishDraft(confirmFirst = false) {
    if (confirmFirst && !window.confirm("Publish these changes to the live site now?")) return;
    setNotice("Publishing…");
    try { await api("/api/admin/settings", "PUT", { mode: "publish" }); await fetch("/api/admin/preview?off=1"); await reload(); flash("Published — your changes are live."); } catch (err) { setError(err instanceof Error ? err.message : "Publish failed."); setNotice(""); }
  }
  async function discardDraft() {
    if (!window.confirm("Discard the draft changes? The live site stays as it is.")) return;
    try { await api("/api/admin/settings", "PUT", { mode: "discard" }); await fetch("/api/admin/preview?off=1"); await reload(); flash("Draft discarded."); } catch (err) { setError(err instanceof Error ? err.message : "Discard failed."); }
  }
  const currentOrder = modal?.resource === "order" ? modal.item as AdminOrder : null;
  const currentCustomer = modal?.resource === "customer" ? modal.item as AdminCustomer : null;
  const currentMessage = modal?.resource === "message" ? modal.item as AdminMessage : null;
  const editorResource = modal && ["products", "categories", "coupons", "faqs", "testimonials"].includes(modal.resource) ? modal.resource : null;
  return <div className="admin-shell"><aside className="admin-sidebar"><Link href="/admin" className="brand">softly<span className="brand-dot">.</span></Link>
    {/* draft controls */}<div className="admin-sidebar-label">WORKSPACE</div><nav className="admin-nav">{nav.map(({ id, label, icon: Icon }) => <button key={id} onClick={() => switchTab(id)} className={tab === id ? "active" : ""} title={label}><Icon size={17} strokeWidth={1.8} /><span>{label}</span>{id === "messages" && data?.messages.some((message) => message.status === "unread") && <span style={{ marginLeft: "auto", background: "#e5aa9b", borderRadius: 20, padding: "2px 6px", color: "#fff", fontSize: 9 }}>{data.messages.filter((message) => message.status === "unread").length}</span>}</button>)}</nav><div className="admin-sidebar-bottom"><Link href="/admin/guide"><BookOpen size={15} /> <span>Admin guide</span></Link><Link href="/" target="_blank" style={{ marginTop: 4 }}><ExternalLink size={15} /> <span>View storefront</span></Link><div style={{ marginTop: 16 }}><LogoutButton admin /></div><a href="https://www.azeemx.dev" target="_blank" rel="noopener noreferrer" style={{ marginTop: 14, fontSize: 10, color: "#8faea0" }}><span>by azeemx.dev</span></a></div></aside><div className="admin-main"><div className="admin-topbar">
      <div style={{ display: "flex", alignItems: "center", gap: 14, flexWrap: "wrap" }}><small>SOFTLY STUDIO &nbsp;/&nbsp; {tab.toUpperCase()}</small>
        {hasDraft && <span className="draft-bar"><span className="draft-dot" /><strong>Unpublished draft</strong><button className="button button-small button-outline" onClick={() => { window.location.href = "/api/admin/preview"; }}><Eye size={13} /> Preview changes</button><button className="button button-small" onClick={() => publishDraft(true)}><Upload size={13} /> Publish now</button><button className="button button-small button-outline" onClick={discardDraft}><X size={13} /> Discard</button></span>}
      </div>
      <div className="admin-user"><span>Hi, {adminName.split(" ")[0]}</span><span className="admin-avatar">{adminName[0]?.toUpperCase()}</span></div>
    </div><div className="admin-content"><div className="admin-title-row"><div><h1>{titles[tab]}</h1><p>{descriptions[tab]}</p></div>{tab === "dashboard" && <Link className="button button-small button-outline" href="/" target="_blank">View live site <ArrowUpRight size={14} /></Link>}</div>{notice && <div className="notice" style={{ marginBottom: 20 }}>{notice}</div>}{error && <div className="notice demo" style={{ marginBottom: 20 }}>{error} <button onClick={() => setError("")} style={{ border: 0, background: "none", float: "right" }}>×</button></div>}{loading ? <div className="admin-panel admin-empty" style={{ padding: 80 }}>Loading your studio...</div> : !data ? <div className="admin-panel admin-empty">Could not load dashboard. <button className="text-link" onClick={() => reload().catch((err) => setError(err.message))}>Try again</button></div> : <>{tab === "dashboard" && dashboard()}{tab === "products" && productList()}{tab === "categories" && categoryList()}{tab === "orders" && orderList()}{tab === "customers" && customerList()}{tab === "coupons" && couponList()}{tab === "content" && content()}{tab === "messages" && messages()}{tab === "subscribers" && subscribers()}{tab === "settings" && settings()}</>}</div></div>
    {editorResource && data && <Modal title={`${modal?.item ? "Edit" : "Add"} ${editorResource === "products" ? "journal" : editorResource === "faqs" ? "FAQ" : editorResource.slice(0, -1)}`} onClose={() => setModal(null)}>{editorResource === "products" ? <ProductEditor product={modal?.item as AdminProduct | undefined} categories={data.categories} onSave={saveProduct} onClose={() => setModal(null)} onDeleteImage={async (id) => { await api(`/api/admin/images/${id}`, "DELETE"); await reload(); }} /> : <GenericEditor resource={editorResource as "categories" | "coupons" | "faqs" | "testimonials"} item={modal?.item as Record<string, unknown> | undefined} onSave={(payload) => saveGeneric(editorResource, modal?.item as { id?: string } | undefined, payload)} onClose={() => setModal(null)} />}</Modal>}
    {currentOrder && <Modal title={`Order ${currentOrder.orderNumber}`} onClose={() => setModal(null)}><div className="admin-form"><div className="form-grid"><div><span className="field-label">Customer</span><strong>{currentOrder.customerName}</strong><p className="muted" style={{ fontSize: 11 }}>{currentOrder.email}</p></div><div><span className="field-label">Placed on</span><strong>{formatDate(currentOrder.createdAt)}</strong><p><Status value={currentOrder.paymentStatus} /> &nbsp; <Status value={currentOrder.status} /></p></div></div><hr className="divider" /><h3>Journals</h3>{currentOrder.items.map((item) => <div key={item.id} className="summary-line"><span>{item.productName} <small>({item.downloads} downloads)</small></span><strong>{formatPrice(item.unitPrice)}</strong></div>)}<hr className="divider" /><div className="summary-line"><span>Subtotal</span><strong>{formatPrice(currentOrder.subtotal)}</strong></div>{currentOrder.discount > 0 && <div className="summary-line"><span>Discount {currentOrder.couponCode && `(${currentOrder.couponCode})`}</span><strong>-{formatPrice(currentOrder.discount)}</strong></div>}<div className="summary-line"><strong>Total</strong><strong>{formatPrice(currentOrder.total)}</strong></div><div className="admin-help">Provider: {currentOrder.provider} · Transaction: {currentOrder.transactionId || "Pending"}</div><div className="admin-form-actions">{currentOrder.paymentStatus === "paid" && <button className="button button-outline button-small" onClick={() => action("orders", currentOrder.id, { action: "refund" }, "Refund this order? This will revoke download access and request a Stripe refund when applicable.")}>Refund order</button>}{currentOrder.paymentStatus === "pending" && <button className="button button-outline button-small" onClick={() => action("orders", currentOrder.id, { action: "cancel" }, "Cancel this pending order?")}>Cancel order</button>}<button className="button button-small" onClick={() => setModal(null)}>Done</button></div></div></Modal>}
    {currentCustomer && <Modal title={currentCustomer.name} onClose={() => setModal(null)}><div className="admin-form"><p className="muted" style={{ fontSize: 12 }}>{currentCustomer.email} · Joined {formatDate(currentCustomer.createdAt)}</p><div className="form-grid"><div className="admin-stat"><small>Orders</small><strong>{currentCustomer.orderCount}</strong></div><div className="admin-stat"><small>Total spent</small><strong>{formatPrice(currentCustomer.totalSpent)}</strong></div></div><h3>Purchase history</h3>{data?.orders.filter((order) => order.userId === currentCustomer.id).map((order) => <div className="summary-line" key={order.id}><span>{order.orderNumber} · {formatDate(order.createdAt)}</span><strong>{formatPrice(order.total)}</strong></div>)}{!currentCustomer.orderCount && <p className="muted" style={{ fontSize: 11 }}>No orders yet.</p>}<div className="admin-form-actions"><button className="button button-outline button-small" onClick={() => action("customers", currentCustomer.id, { status: currentCustomer.status === "active" ? "disabled" : "active" }, `${currentCustomer.status === "active" ? "Disable" : "Reactivate"} this account?`)}>{currentCustomer.status === "active" ? "Disable account" : "Reactivate account"}</button><button className="button button-small" onClick={() => setModal(null)}>Done</button></div></div></Modal>}
    {currentMessage && <Modal title={currentMessage.subject} onClose={() => setModal(null)}><div className="admin-form"><p style={{ fontSize: 12 }}><strong>From:</strong> {currentMessage.name} &lt;{currentMessage.email}&gt;</p><p className="muted" style={{ fontSize: 11 }}>{formatDate(currentMessage.createdAt)}</p><div style={{ background: "#f6f8f4", padding: 20, whiteSpace: "pre-wrap", fontSize: 13, lineHeight: 1.8 }}>{currentMessage.message}</div><div className="admin-form-actions"><a className="button button-small" href={`mailto:${currentMessage.email}?subject=Re: ${encodeURIComponent(currentMessage.subject)}`}>Reply by email <ArrowRight size={13} /></a></div></div></Modal>}
  </div>;
}
