"use client";

import { useEffect, useState, type FormEvent } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { ArrowRight } from "lucide-react";

type Mode = "login" | "register" | "forgot" | "reset" | "verify";
export default function AuthForm({ mode, token = "", admin = false, demoMode = false }: { mode: Mode; token?: string; admin?: boolean; demoMode?: boolean }) {
  const router = useRouter(); const [name, setName] = useState(""); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [error, setError] = useState(""); const [message, setMessage] = useState(""); const [loading, setLoading] = useState(false);
  useEffect(() => { if (mode !== "verify" || !token) return; let active = true; fetch("/api/auth/verify", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ token }) }).then((response) => response.json().then((data) => ({ ok: response.ok, data }))).then(({ ok, data }) => { if (active) { if (ok) setMessage(data.message); else setError(data.error); } }).catch(() => { if (active) setError("Could not verify your email."); }); return () => { active = false; }; }, [mode, token]);
  async function submit(event: FormEvent) { event.preventDefault(); setError(""); setMessage(""); setLoading(true); try { const response = await fetch(`/api/auth/${mode}`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name, email, password, token }) }); const data = await response.json(); if (!response.ok) setError(data.error || "Something went wrong."); else if (mode === "forgot") setMessage(data.message); else { router.push(admin ? "/admin" : "/account"); router.refresh(); } } catch { setError("Could not connect. Please try again."); } setLoading(false); }
  const titles: Record<Mode, string> = { login: admin ? "Welcome back, admin." : "Welcome back.", register: "Make yourself at home.", forgot: "Let's find your way back.", reset: "A fresh start.", verify: "Confirm your email." };
  const descriptions: Record<Mode, string> = { login: admin ? "Sign in to manage your little corner of the internet." : "Sign in to find your journals and pick up where you left off.", register: "Create an account to keep all your journals in one cozy place.", forgot: "Enter your email and we'll send you a link to reset your password.", reset: "Choose a new password for your account.", verify: "We're checking your verification link." };
  return <div className="auth-card"><span className="eyebrow">{admin ? "SOFTLY STUDIO" : "YOUR SPACE"}</span><h1>{titles[mode]}</h1><p>{descriptions[mode]}</p>{admin && demoMode && mode === "login" && <div className="demo-credentials"><strong>Preview admin access</strong><br />Email: hello@softly.studio<br />Password: SoftlyDemo2026!<br /><small>Only available when payment keys are not configured.</small></div>}{mode === "verify" ? <div>{error && <p className="form-error" role="alert">{error}</p>}{message ? <p className="form-success">{message}</p> : !error && <p className="muted">One moment...</p>}<Link className="button" href="/account">Go to my account <ArrowRight size={14} /></Link></div> : <form onSubmit={submit}>{mode === "register" && <div className="field"><label className="field-label" htmlFor="auth-name">Your name</label><input className="input" id="auth-name" autoComplete="name" required minLength={2} value={name} onChange={(event) => setName(event.target.value)} placeholder="What should we call you?" /></div>}{["login", "register", "forgot"].includes(mode) && <div className="field"><label className="field-label" htmlFor="auth-email">Email address</label><input className="input" id="auth-email" type="email" autoComplete="email" required value={email} onChange={(event) => setEmail(event.target.value)} placeholder="you@example.com" /></div>}{["login", "register", "reset"].includes(mode) && <div className="field"><label className="field-label" htmlFor="auth-password">{mode === "reset" ? "New password" : "Password"}</label><input className="input" id="auth-password" type="password" autoComplete={mode === "login" ? "current-password" : "new-password"} minLength={mode === "login" ? undefined : 8} required value={password} onChange={(event) => setPassword(event.target.value)} placeholder={mode === "login" ? "Your password" : "At least 8 characters"} /></div>}{mode === "login" && !admin && <Link className="auth-forgot" href="/account/forgot-password">Forgot password?</Link>}{error && <p className="form-error" role="alert">{error}</p>}{message && <p className="form-success" role="status">{message}</p>}<button type="submit" className="button" disabled={loading || (mode === "reset" && !token)}>{loading ? "Just a moment..." : mode === "login" ? "Sign in" : mode === "register" ? "Create account" : mode === "forgot" ? "Send reset link" : "Update password"}<ArrowRight size={15} /></button></form>}{mode === "login" && !admin && <div className="auth-bottom">New around here? <Link href="/account/register">Create an account</Link></div>}{mode === "register" && <div className="auth-bottom">Already have an account? <Link href="/account/login">Sign in</Link></div>}{mode === "forgot" && <div className="auth-bottom">Remembered it? <Link href="/account/login">Back to sign in</Link></div>}</div>;
}
